on:
  workflow_dispatch:

name: Build

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MSVC environment
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64

      - name: Compile WinTUN
        run: |
          msbuild driver/driver.vcxproj /p:Configuration=Release /p:Platform=x64
          msbuild api/api.vcxproj /p:Configuration=Release /p:Platform=x64

      - uses: actions/upload-artifact@v4
        with:
          name: wintun-x64
          path: ./Release/amd64/
